name: flutter_secure_biometrics
description: Advanced biometric authentication plugin with app-specific isolation, multi-modal authentication, and continuous security monitoring.
version: 1.0.0
homepage: https://github.com/your-org/flutter_secure_biometrics

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.7
  crypto: ^3.0.3
  convert: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mockito: ^5.4.2
  build_runner: ^2.4.7

flutter:
  plugin:
    platforms:
      android:
        package: com.example.flutter_secure_biometrics
        pluginClass: FlutterSecureBiometricsPlugin
      ios:
        pluginClass: FlutterSecureBiometricsPlugin

topics:
  - biometrics
  - security
  - authentication
  - privacy
  - enterprise
